/*
 * This file is generated by jOOQ.
 */
package com.falsework.account.model;


import com.falsework.account.model.tables.TUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in testdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>testdb.t_user</code>.
     */
    public static final TUser T_USER = com.falsework.account.model.tables.TUser.T_USER;
}
