/*
 * This file is generated by jOOQ.
 */
package com.falsework.account.model;


import com.falsework.account.model.tables.TUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testdb extends SchemaImpl {

    private static final long serialVersionUID = -1682483789;

    /**
     * The reference instance of <code>testdb</code>
     */
    public static final Testdb TESTDB = new Testdb();

    /**
     * The table <code>testdb.t_user</code>.
     */
    public final TUser T_USER = com.falsework.account.model.tables.TUser.T_USER;

    /**
     * No further instances allowed
     */
    private Testdb() {
        super("testdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TUser.T_USER);
    }
}
